version: "3.7" 
services:
  blog-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      DEBUG: knex*
    depends_on:
      - oracle

  oracle: 
    image: oracle-xe-11g:latest
    restart: always
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: blog_app
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d/
